<?php 
/**
 *
 * @category   MW
 * @package    MW_Credit
 * @author Mage World <support@mage-world.com>
 */
 ?>
<?php $order = Mage::registry('current_order');?>
<?php if(!$order) $order = $this->getParentBlock()->getOrder();?>
<?php $credit = Mage::helper('credit')->getCreditByOrder($order)?>
<?php if($credit):?>
	<?php $money = Mage::helper('credit')->exchangeCreditToMoney($credit);?>
	<tr class="2">
	    <td  class="label" >Credit</td>
	    <td ><span class="price"><?php echo Mage::helper('credit')->formatMoney($money)?></span></td>
	</tr>
<?php endif;?>