<link href="<?php echo $this->getSkinUrl('Customerpartner/css/global.css'); ?>" rel="stylesheet" type="text/css" />
<script type="text/javascript">
if (typeof jQuery == 'undefined')
{
    document.write(unescape("%3Cscript src='http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js' type='text/javascript'%3E%3C/script%3E"));
}
</script> 
<script src="<?php echo $this->getSkinUrl('Customerpartner/js/nicEdit-latest.js'); ?>" type="text/javascript"></script>
<script type="text/javascript">
//<![CDATA[
  bkLib.onDomLoaded(function() {
        
        new nicEditor({fullPanel : true}).panelInstance('description');
        new nicEditor({fullPanel : true}).panelInstance('short_description');
       
  });
  //]]>
  </script>
<script src="<?php echo Mage::getBaseUrl('js').'calendar/calendar.js';?>" type="text/javascript"></script>
<script src="<?php echo Mage::getBaseUrl('js').'calendar/calendar-setup.js';?>" type="text/javascript"></script>
<?php
$url= $_SERVER['REQUEST_URI'];
$urlarr=explode('/',$url);
if($urlarr[10]=="approved")
	{}	
else
	{?>
				<?php
				echo $this->getMessagesBlock()->getGroupedHtml();
				$product = $this->getProduct();
				?>
				<?php		
							/****** here i code for mysql prefix *****/
							$mysqlprefix=Mage::getStoreConfig('partners/partners_options/mysqlprefix');
							$mysqlprefixlen=strlen(Mage::getStoreConfig('partners/partners_options/mysqlprefix'));
							/****** end here i code for mysql prefix *****/
							$write = Mage::getSingleton('core/resource')->getConnection('core_write');
							/****** here i code for mysql prefix checking and execute code*****/
							$querydata=$write->query("SELECT * FROM ".$mysqlprefix."customerpartner_entity_data where customerpartnerproductid='".$product['entity_id']."'");
							/** end **/
							#$querydata=$write->query("SELECT * FROM customerpartner_entity_data where customerpartnerproductid='".$product['entity_id']."'");
							$rowdata=$querydata->fetch();
				?>
	<div class="prdouctbackground">		
		<form action="<?php echo $this->getUrl('customer/products/editsimplePost') ?>" enctype="multipart/form-data" method="post" id="form-customer-product-editPost">
						<input type="hidden" name="productid" value="<?php echo $product['entity_id']?>" />
						<fieldset class="group-select" >
							<div id="customerpartner-products">
								<h4 class="textcolor"><?php echo $this->__('Edit Simple Product') ?></h4>
								<table class="tablepostion" >
									 <thead>
										<tr>
										  <th colspan="2" class="headingbg">Product Information</th>
										</tr>
										
									</thead>
									<tbody id="tbodying">

										<tr>
											<td class="tdpadfirst">
												<label for="category" class="rightgap"><?php echo $this->__('Product Category :') ?></label><span class="required starimp">&nbsp;&nbsp;&nbsp;&nbsp;</span>
											</td>
											<td class="tdpadsec">
												<select id="category" class="myinput-text required-entry widthinput" name="category"   >
													<?php $_helper = Mage::helper('catalog/category'); ?>
																<?php $_categories = $_helper->getStoreCategories() ;?>
																<?php if (count($_categories) > 0): ?>
																<?php foreach($_categories as $_category): ?>
																						<?php if($_category['entity_id']==$rowdata['category']){?>
																							<option selected="selected" name="<?php echo $_category['entity_id']?>" value="<?php echo $_category['entity_id']?>"><?php echo $_category->getName();?></option>
																						<?php }
																						else {?>
																						
																						<option  name="<?php echo $_category['entity_id']?>" value="<?php echo $_category['entity_id']?>"><?php echo $_category->getName();?></option>
																						<?php }?>
																		<?php endforeach; ?>
																<?php endif; ?>
												</select>
											</td>
										</tr>
										<tr>
											<td class="tdpadfirst">
												<label for="name" class="rightgap"><?php echo $this->__('Product Name :')?></label> <span class="required starimp">&nbsp;&nbsp;&nbsp;&nbsp;</span>
											</td>
											<td class="tdpadsec">
												<input type="name" class="required-entry widthinput" name="name" id="name" value="<?php echo $product['name']?>" />
											</td>
										</tr>
										<tr>
											<td class="tdpadfirst">
												<label for="description" class="rightgap"><?php echo $this->__('Description :') ?></label><span class="required starimp">&nbsp;&nbsp;&nbsp;&nbsp;</span>
											</td>
											<td class="tdpadsec">
												<textarea name="description" class="required-entry " id="description" rows="5" cols="75" ><?php echo $product['description']?></textarea>
											</td>
										</tr>
										<tr>
											<td class="tdpadfirst">
												<label for="short_description" class="rightgap"><?php echo $this->__('Short description :') ?></label><span class="required starimp">&nbsp;&nbsp;&nbsp;&nbsp;</span>
											</td>
											<td class="tdpadsec">
												<textarea name="short_description" id="short_description" rows="5" cols="75" class="required-entry input-text"><?php echo $product['short_description']?></textarea>
											</td>
										</tr>
										<tr>
											<td class="tdpadfirst">
												<label for="sku" class="rightgap"><?php echo $this->__('SKU :') ?></label><span class="required starimp">&nbsp;&nbsp;&nbsp;&nbsp;</span>
											</td>
											<td class="tdpadsec">
												<input name="sku" id="sku" class=" required-entry widthinput" value="<?php echo $rowdata['sku']?>"/>
												<div id="skuavail" ><img src="<?php echo $this->getSkinUrl('customerurlpic/available.png'); ?>"/><span>SKU Available</span></div>
												<div id="skunotavail" ><img src="<?php echo $this->getSkinUrl('customerurlpic/x-mark.jpg'); ?>"/><span>SKU Already Exist</span></div>
											</td>
										</tr>
										
										<tr>
											<td class="tdpadfirst">
												<label for="price" class="rightgap"><?php echo $this->__('Price :') ?></label><span class="required starimp">&nbsp;&nbsp;&nbsp;&nbsp;</span>
											</td>
											<td class="tdpadsec">
												<input type="price" class=" required-entry widthinput" name="price" id="price" value="<?php echo $product['price']?>"/>
											</td>
										</tr>
										<tr>
											<td class="tdpadfirst">
												<label for="stock" class="rightgap"><?php echo $this->__('Stock :') ?></label><span class="required starimp">&nbsp;&nbsp;&nbsp;&nbsp;</span>
											</td>
											<td class="tdpadsec">
												<input type="stock" class=" required-entry widthinput" name="stock" id="stock" value="<?php echo $product['stock']?>"/>
											</td>
										</tr>
										<tr>
											<td class="tdpadfirst">
												<label for="weight" class="rightgap"><?php echo $this->__('Weight :') ?></label><span class="required starimp">&nbsp;&nbsp;&nbsp;&nbsp;</span>
											</td>
											<td class="tdpadsec">
												<input type="weight" class=" required-entry widthinput" name="weight" id="weight"  value="<?php echo $product['weight']?>"/>
											</td>
										</tr>
										<tr>
											<td class="tdpadfirst">
												<label for="file" class="rightgap"><?php echo $this->__('Image') ?></label><span class="required starimp">&nbsp;&nbsp;&nbsp;&nbsp;</span>
											</td>
											<td class="tdpadsec">
												<input type="file" name="images" size="33" ><br clear="all"/>
												<a href="#" onClick="showOtherImage(); return false;">Add other image</a><br />
												<div id="otherimages"></div>
											</td>
										</tr>
									</tbody>	
								</table>
							</div>
							<div class="button-set buttonarea">
								<p class="headingbackindex">
									<a href="javascript:;" onclick="javascript: window.history.back();" class="left">&laquo; <?php echo $this->__('Back') ?></a>
								</p>
								<center>
									<button type="submit" class="form-button btn"><span><?php echo $this->__('Save') ?></span></button>
								</center>
							</div>
						</fieldset>
		</form>
	</div>
<?php } ?>
<!--
end new product
-->

<script> 
jQuery.noConflict();
	jQuery('input#sku').change(function(){
		var len=jQuery('input#sku').val();
		var len2=len.length;
		if(len2==0){
			//jQuery("input#sku").focus();
			alert("SKU can't be left empty");
			jQuery('div#skuavail').css('display','none');
			jQuery('div#skunotavail').css('display','none');
		}
		else{
			jQuery.ajax({
					url: "<? echo  Mage::getBaseUrl('skin');?>recive.php",
					type: "POST",
					data: {sku:jQuery('input#sku').val()},
					dataType: 'html',
					success:function(content){//alert(content);
						if(content==0){
							jQuery('div#skuavail').css('display','block');
							jQuery('div#skunotavail').css('display','none');
						}
						else{
							jQuery('div#skunotavail').css('display','block');
							jQuery('div#skuavail').css('display','none');
							jQuery("input#sku").attr('value','');
						}
					}
			});
		}
	});
</script>	
<script type="text/javascript">
	var newCustomerProductForm = new VarienForm('form-customer-product-editPost', true);

	var i=2;
	function showOtherImage() {
		var newdiv = document.createElement('div');
		newdiv.setAttribute("id","childDiv"+i);
		newdiv.innerHTML = "<input type='file' name='images"+i+"' /><a href=\"javascript:;\" onclick=\"removeEvent('childDiv"+i+"')\">Remove</a>";
		var ni = document.getElementById('otherimages');
		ni.appendChild(newdiv);
		i++;
	}

	function removeEvent(divNum)
	{
		var d = document.getElementById('otherimages');
		var olddiv = document.getElementById(divNum);
		d.removeChild(olddiv);
		i--;
	}
</script>
