<link href="<?php echo $this->getSkinUrl('Customerpartner/css/global.css'); ?>" rel="stylesheet" type="text/css" />
<link href="<?php echo $this->getSkinUrl('Customerpartner/css/stylespagination.css'); ?>" rel="stylesheet" type="text/css" />
<script type="text/javascript">
if (typeof jQuery == 'undefined'){
    document.write(unescape("%3Cscript src='http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js' type='text/javascript'%3E%3C/script%3E"));
}
</script>
<script src="<?php echo $this->getSkinUrl('Customerpartner/js/jquery.pajinate.js'); ?>" type="text/javascript"></script>
<?php $products = $this->getProducts(); 
#echo strlen(Mage::getStoreConfig('partners/partners_options/mysqlprefix'));?>
<div class="prdouctbackground">
	<fieldset class="group-select">		
		<div id="customerpartner-products">
			<h4 class="textcolor"><?php echo $this->__('Edit Product') ?></h4>
			<div id="paging_container7">
				<div class="page_navigation"></div>
				<p class="headingbg">Product Information</p>
				<table class="" id="one-column-emphasis">
					<thead class="">
						<tr>										
							<th class="">
								<label for="name" class="head"><?php echo $this->__('Product Name')?></label> 
							</th>
							<th class="">
								<label for="name"  class="head"><?php echo $this->__('Image')?></label> 
							</th>
							<th class="">
								<label for="name"  class="head"><?php echo $this->__('Price')?></label> 
							</th>
							<th class="">
								<label for="name" class="head"><?php echo $this->__('Weight')?></label> 
							</th>
							<th class="">
								<label for="name" class="head"><?php echo $this->__('Stock')?></label> 
							</th>
							<th class="">
								<label for="name" class="head"><?php echo $this->__('Status')?></label> 
							</th>
							<th class="">
								<label for="name" class="head"><?php echo $this->__('Qty. Sold')?></label> 
							</th>
							<th class="">
								<label for="name" class="head"><?php echo $this->__('Earned')?></label> 
							</th>
							<th class="">
								<label for="name" class="head"><?php echo $this->__('Owned')?></label> 
							</th>
							<th class="">
								<label for="name" class="head"><?php echo $this->__('Action')?></label> 
							</th>
						</tr>	
					</thead>
					<tbody class="">
						<?php 		
									$checkeven=0;
									$i=0;
									foreach ($products as $p){?>
										<tr class="<?php if($checkeven%2==0)echo 'even-prod';else echo 'odd-prod';?> ex2">
											<td class=""><label for="name" class="blue"><?php ((strlen($p['name'])) > 7) ? substr($p['name'], 0, 7)."..." : $p['name'];  ?>
											<?php $l=strlen($p['name']); if($l>7){ echo substr($p['name'],0,7)."..";}else {echo $p['name'];} ?>
											</label></td>
											<?php if($p['image']){?>
												<td class=""><img src="<?php echo $p['image']?>" width="45px" height="35px" /></td>			
											<?php
											}
											else{
											?>
												<td class=""><label for="name" class="">Pending</label></td>
											<?php
											}
											?>
											<td class=""><label for="name" class=""><?php echo Mage::app()->getStore()->formatPrice($p['price'])?></label></td>
											<td class=""><label for="name" class=""><?php echo sprintf("%01.2f", $p['weight'])?></label></td>
											<td class=""><label for="name" class=""><?php echo $p['stock']?></label></td>
												<?php
												if($p['product_id']==0) {
													
													?>
													<?php 
															$write = Mage::getSingleton('core/resource')->getConnection('core_write');
															$readresult=$write->query("select producttype from customerpartner_entity_data where customerpartnerproductid ='".$p['entity_id']."'");
															$row = $readresult->fetch();
															#echo $row['producttype'];
														?>
													<td  class=""><label for="name" class="">pending</label></td>
													<td  class=""><label for="name" class="">pending</label></td>
													<td  class=""><label for="name" class="">pending</label></td>
													<td  class=""><label for="name" class="">pending</label></td>
													<td style="text-align:center;" class=""><label for="name" class=""><a title="Edit" onclick="editme('<?php echo $p['entity_id']; ?>','<?php echo $row['producttype']; ?>')"><img src="<?php echo $this->getSkinUrl('customerurlpic/edit.gif'); ?>" /></a></label></td>	
												<?php
												} else
												{
												?>
													<td class=""><label for="name" class="">approved</label></td>
													<?php
													$QtyandEarned = $this->getQtySoldandEarned($p['entity_id']);
													?>
													<td align="center" class=""><label for="name" class=""><?php echo $QtyandEarned['qtySold']?></label></td>
													<td align="center" class=""><label for="name" class=""><?php echo Mage::app()->getStore()->formatPrice($QtyandEarned['earned'])?></label></td>
													<td align="center" class=""><label for="name" class=""><?php echo Mage::app()->getStore()->formatPrice($QtyandEarned['owed'])?></label></td>
													<td style="text-align:center;" class=""><label class=""></label></td>
												<?php
												}
												?>
										</tr>
									 <?php
										$checkeven++;
									} 
									 ?>
					</tbody>	
				</table>
				<p class="headingback">
					<a href="javascript:;" onclick="javascript: window.history.back();" class="left">&laquo; <?php echo $this->__('Back') ?></a>
				</p>
			</div>	
		</div> 
	</fieldset>
</div>
<script type="text/javascript">
	jQuery.noConflict();	
	jQuery(document).ready(function(){
		jQuery('#paging_container7').pajinate({
			num_page_links_to_display : 5,
			items_per_page : 10	
		});
	});	
	
</script>
<script>
	function editme(pid,producttype)	{
		if(producttype=='simple')
			{window.location = "<?php echo $this->getUrl('customer/products/editsimple/') ?>".concat("id/",pid,"/");}
		if(producttype=='virtual')
			{window.location = "<?php echo $this->getUrl('customer/products/editvirtual/') ?>".concat("id/",pid,"/");}
		if(producttype=='downloadable')
			{window.location = "<?php echo $this->getUrl('customer/products/editdownload/') ?>".concat("id/",pid,"/");}		
						
	}
</script>