<?php

?>
<div class="page-head">
    <h3><?php echo $this->__('Customer profile') ?></h3>
</div>
<?php
	echo $this->getMessagesBlock()->getGroupedHtml();
	$profileShort = $this->htmlEscape($this->getCustomer()->getShortprofile());
	$gender = $this->htmlEscape(ucwords($this->getCustomer()->getGender()));

	$reviews = $this->getReviews();
?>

<fieldset class="group-select">
    <table width="100%">
    	<tr>
    		<td>
				<ul>
			        <li>
			            <?php echo $this->__('Screen name') ?>: <?php echo $this->htmlEscape($this->getCustomer()->getNickname()) ?><br />
			        </li>
			        <?php if(!empty($gender)): ?>
			        <li>
						<?php echo $this->__('Gender') ?>: <?php echo $gender; ?><br />
			        </li>
			        <?php endif; ?>
			        <?php if(!empty($profileShort)): ?>
			        <li>
			            <?php echo $this->__('Short profile') ?>: <?php echo $profileShort; ?><br />
			        </li>
			        <?php endif; ?>
			    </ul>
    		</td>
    		<td width="40%" align="center">
    			<?php echo $this->getAvatar( $this->getCustomer()->getId() ); ?>
    		</td>
    	</tr>
    </table>

	<div id="customer-reviews">
		<h4><?php echo $this->__('My Product Reviews') ?></h4>
	<?php if($reviews && $reviews->count()): ?>
        <table class="data-table box-table" id="reviews-table" cellspacing="0">
            <col width="60" />
            <col width="200" />
            <col width="80" />
            <col />
            <col width="100" />
            <tbody>
                <?php foreach ($reviews as $_review): ?>
                <tr>
                    <td><?php echo $this->helper('core')->formatDate($_review->getCreatedAt(), Mage_Core_Model_Locale::FORMAT_TYPE_SHORT); ?></td>
                    <td><a href="<?php echo Mage::getUrl('catalog/product/view/'); ?>id/<?php echo $_review->getEntityPkValue() ?>"><?php echo $this->htmlEscape($_review->getName()) ?></a></td>
                    <td>
                    <?php if($_review->getSum()): ?>
                        <div class="rating-box">
                            <div class="rating" style="width:<?php echo ( $_review->getSum() / $_review->getCount() ) ?>%;"></div>
                        </div>
                    <?php endif; ?>
                    </td>
                    <td><?php echo $this->htmlEscape($this->helper('review')->getDetail($_review->getDetail())) ?></td>
                    <td class="last a-center"><a href="<?php echo Mage::getUrl('review/customer/view/') ?>id/<?php echo $_review->getReviewId() ?>"><?php echo $this->__('View Details') ?></a></td>
                </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
      <?php else: ?>
      	<p><?php echo $this->__('No reviews found.') ?></p>
      <?php endif; ?>
	</div>

</fieldset>

<a href="<?php echo $this->getBackUrl() ?>" class="left">&laquo; <?php echo $this->__('Back') ?></a>