<?php
$currentProduct = Mage::registry('current_product');
$currentProductId = 0;
$exclude = array();
if($currentProduct){
    $exclude[] = $currentProduct->getId();
}
?>
<?php
$_data = $this->getProducts($exclude);
$_products = $_data['products'];
?>
<?if(count($_data['products'])):?>
    <div class="navbar-inner pull-left" style="width: 100%;padding: 0px;">
        <h2 class="more-deals">More <?php echo  $this->helper('deal')->getProductCategoryName($currentProduct);?> Deals</h2>
    </div>
<?php endif;?>
<?php
$i = 1;
foreach ($_products as $_productId):
    $_product = Mage::getModel('catalog/product')->load($_productId);
    Mage::register('product', $_product,true);
    $_block = Mage::getBlockSingleton('Web_Deal_Block_Catalog_Product_View');
    $_block->getDealInfo();
    $cat = $_block->getParentCat();
    $url = $this->helper('deal')->getFullProductUrl($_product);
    $discount = (int) (($_product->getOriginalPrice() - $_product->getPrice()) / $_product->getOriginalPrice() * 100);
    $end_date = strtotime($_product->getEndDate());
    $toDate = time();
    $sec_diff = ($end_date - $toDate);
    $time = Mage::helper('deal')->secondsToTime($sec_diff);
    ?>
    <div id="deal-<?php echo $_product->getId();?>" class="deal">
        <h3>
            <a class="view" href="<?php echo $url;?>"><?php echo $_product->getShortName();?></a>
        </h3>

        <div class="pre photo"><a href="<?php echo $url;?>"><img class="lazy" src="<?php echo $this->getSkinUrl('images/deals-loader.gif'); ?>" data-src="<?php echo $this->helper('catalog/image')->init($_product, 'image')->constrainOnly(TRUE)
                    ->keepAspectRatio(false)
                    ->keepFrame(true)->resize(320, 205); ?>"></a></div>

        <div class="price-info">
            <div><span class="title">Discount</span><span class="value"> <?php echo $discount;?>%</span></div>
            <div><span class="title">Value</span><span class="value"><?php echo $_block->getPriceCurrency($_product->getOriginalPrice());?></span></div>
            <div><span class="title">Price</span><span class="value"> <?php echo $_block->getPriceCurrency($_product->getPrice());?></span></div>
        </div>


        <div class="extra" style="">

            <div class="btns">
                <a href="javascript:void(0);" class="btn btn-g" style="margin-top:30px"><i class="icon-shopping-cart icon-white"></i> Buy </a>
                <div class="clr"></div>
                <a href="<?php echo $url;?>" class="btn btn-g btn-small" style=""><i class="icon-eye-open icon-white"></i> View </a>

            </div>

            <div class="countdown">
                Remaining
                <div id="remaining-<?php echo $sec_diff;?>>" class="hasCountdown"><span class="countdown_row countdown_show3"><span class="countdown_section"><span class="countdown_amount"><?php echo $time['d'];?></span><br>Days</span><span class="countdown_section"><span class="countdown_amount"><?php echo $time['h'];?></span><br>Hours</span><span class="countdown_section"><span class="countdown_amount"><?php echo $time['m'];?></span><br>Minutes</span></span></div>
            </div>

            <div class="bought"><?php echo $_block->ordered_qty;?> bought this deal
                <div class="clr"></div>

                <a href="javascript:void(0);" class="btn btn-g btn-small"><i class="icon-heart icon-white"></i></a>
                <a href="javascript:void(0);" class="btn btn-g btn-small"><i class="icon-share icon-white"></i></a>

                <a href="<?php echo $cat->getUrl();?>" class="btn btn-g btn-small"><i class="icon-tag icon-white"></i> <?php echo $cat->getName();?> </a>

            </div>

        </div>
    </div>
    <?php $i++; endforeach; ?>

<?php
$_data = $this->getOtherProducts($exclude);
$_products = $_data['products'];
?>
<?if(count($_data['products'])):?>
    <div class="navbar-inner pull-left" style="width: 100%;padding: 0px;">
        <h2 class="more-deals">More Daily Deals</h2>
    </div>
<?php endif;?>
<?php
$i = 1;
foreach ($_products as $_productId):
    $_product = Mage::getModel('catalog/product')->load($_productId);
    Mage::register('product', $_product,true);
    $_block = Mage::getBlockSingleton('Web_Deal_Block_Catalog_Product_View');
    $_block->getDealInfo();
    $cat = $_block->getParentCat();
    $url = $this->helper('deal')->getFullProductUrl($_product);
    $discount = (int) (($_product->getOriginalPrice() - $_product->getPrice()) / $_product->getOriginalPrice() * 100);
    $end_date = strtotime($_product->getEndDate());
    $toDate = time();
    $sec_diff = ($end_date - $toDate);
    $time = Mage::helper('deal')->secondsToTime($sec_diff);
    ?>
    <div id="deal-<?php echo $_product->getId();?>" class="deal">
        <h3>
            <a class="view" href="<?php echo $url;?>"><?php echo $_product->getShortName();?></a>
        </h3>

        <div class="pre photo"><a href="<?php echo $url;?>"><img class="lazy" src="<?php echo $this->getSkinUrl('images/deals-loader.gif'); ?>" data-src="<?php echo $this->helper('catalog/image')->init($_product, 'image')->constrainOnly(TRUE)
                    ->keepAspectRatio(false)
                    ->keepFrame(true)->resize(320, 205); ?>"></a></div>

        <div class="price-info">
            <div><span class="title">Discount</span><span class="value"> <?php echo $discount;?>%</span></div>
            <div><span class="title">Value</span><span class="value"><?php echo $_block->getPriceCurrency($_product->getOriginalPrice());?></span></div>
            <div><span class="title">Price</span><span class="value"> <?php echo $_block->getPriceCurrency($_product->getPrice());?></span></div>
        </div>


        <div class="extra" style="">

            <div class="btns">
                <a href="javascript:void(0);" class="btn btn-g" style="margin-top:30px"><i class="icon-shopping-cart icon-white"></i> Buy </a>
                <div class="clr"></div>
                <a href="<?php echo $url;?>" class="btn btn-g btn-small" style=""><i class="icon-eye-open icon-white"></i> View </a>

            </div>

            <div class="countdown">
                Remaining
                <div id="remaining-<?php echo $sec_diff;?>>" class="hasCountdown"><span class="countdown_row countdown_show3"><span class="countdown_section"><span class="countdown_amount"><?php echo $time['d'];?></span><br>Days</span><span class="countdown_section"><span class="countdown_amount"><?php echo $time['h'];?></span><br>Hours</span><span class="countdown_section"><span class="countdown_amount"><?php echo $time['m'];?></span><br>Minutes</span></span></div>
            </div>

            <div class="bought"><?php echo $_block->ordered_qty;?> bought this deal
                <div class="clr"></div>

                <a href="javascript:void(0);" class="btn btn-g btn-small"><i class="icon-heart icon-white"></i></a>
                <a href="javascript:void(0);" class="btn btn-g btn-small"><i class="icon-share icon-white"></i></a>

                <a href="<?php echo $cat->getUrl();?>" class="btn btn-g btn-small"><i class="icon-tag icon-white"></i> <?php echo $cat->getName();?> </a>

            </div>

        </div>
    </div>
    <?php $i++; endforeach; ?>