<?php if (!($_shippingRateGroups = $this->getShippingRates())): ?>
    <h6><?php echo $this->__('Sorry, no quotes are available for this order at this time.') ?></h6>
<?php else: ?>
<dl >
    <?php $_sole = count($_shippingRateGroups) == 1; foreach ($_shippingRateGroups as $code => $_rates): ?>
        <h6><?php echo $this->getCarrierName($code) ?></h6>
        <dt>
           
            <?php $_sole = $_sole && count($_rates) == 1; foreach ($_rates as $_rate): ?>
           
                   <?php if ($_rate->getErrorMessage()): ?>
                    <ul class="messages"><li class="error-msg"><ul><li><?php echo $_rate->getErrorMessage() ?></li></ul></li></ul>
                   <?php else: ?>
                        <?php if ($_sole) : ?>
                        
                           <span class="no-display"><input name="shipping_method" type="radio" value="<?php echo $_rate->getCode() ?>" id="s_method_<?php echo $_rate->getCode() ?>" checked="checked"  class="radio" /></span>
                        
                        <?php else: ?>
                        <input name="shipping_method" type="radio" value="<?php echo $_rate->getCode() ?>" id="s_method_<?php echo $_rate->getCode() ?>"<?php if($_rate->getCode()===$this->getAddressShippingMethod()) echo ' checked="checked"' ?> class="radio validate-one-required-by-name" />
                        <?php endif; ?>
                      
                        <label for="s_method_<?php echo $_rate->getCode() ?>"><?php echo $_rate->getMethodTitle() ?>
                        <?php $_excl = $this->getShippingPrice($_rate->getPrice(), $this->helper('tax')->displayShippingPriceIncludingTax()); ?>
                        <?php $_incl = $this->getShippingPrice($_rate->getPrice(), true); ?>
                        <?php echo strip_tags($_excl); ?>
                        <?php if ($this->helper('tax')->displayShippingBothPrices() && $_incl != $_excl): ?>
                            (<?php echo $this->__('Incl. Tax'); ?> <?php echo strip_tags($_incl); ?>)
                        <?php endif; ?>
                        </label>
                          <p class="clear"></p>
                   <?php endif ?>
           
            <?php endforeach; ?>
           
        </dt>
    <?php endforeach; ?>
</dl>
<script type="text/javascript">
    //<![CDATA[
        $$('#checkout-shipping-method-load input').invoke('observe', 'click', function(event){shippingMethod.saveShippingMethod();});
    //]]>
</script>
<?php endif; ?>
