<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<?php $_vouchers = $this->getVouchers(); ?>
<div class="page-title">
    <h1><?php echo $this->__('My Vouchers') ?></h1>
</div>
<?php echo $this->getPagerHtml(); ?>
<?php if ($_vouchers->getSize()): ?>
    <table class="data-table" id="my-vouchers-table">
        <col width="1"/>
        <col width="1"/>
        <col width="1"/>
        <col width="1"/>
        <col width="1"/>
        <col width="1"/>
        <col width="1"/>
        <thead>
        <tr>
            <th><?php echo $this->__('Order #') ?></th>
            <th><?php echo $this->__('Date') ?></th>
            <th><?php echo $this->__('Voucher Code') ?></th>
            <th><?php echo $this->__('Product Name') ?></th>

            <th><?php echo $this->__('Status') ?></th>
            <th>&nbsp;</th>
            <!--<th>&nbsp;</th>-->
        </tr>
        </thead>
        <tbody>
            <?php foreach ($_vouchers as $_voucher): ?>
        <tr>
            <td><?php echo $_voucher->getOrderIncrementID() ?></td>
            <td><span class="nobr"><?php echo $this->formatDate($_voucher->getCreatedAtStoreDate()) ?></span></td>
            <td><?php echo $_voucher->getDealVoucherCode() ?></td>
            <td><?php echo $_voucher->getName();?></td>

            <td><em><?php echo ucwords($_voucher->getStatus()) ?></em></td>
            <td class="a-center">
                        <span class="nobr">
                        <a href="<?php echo $this->getViewUrl($_voucher) ?>" target="_blank"><?php echo $this->__('View') ?></a>
                        </span>
            </td>
            <?php /* Removed by VD - 18 feb 2013. Uncomment L25 for colum.
            <td class="a-center">
                        <span class="nobr">
                        <a href="<?php echo $this->getDownloadUrl($_voucher) ?>"><?php echo $this->__('Download') ?></a>
                        </span>
            </td> */?>
        </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
<script type="text/javascript">decorateTable('my-vouchers-table');</script>
<?php echo $this->getPagerHtml(); ?>
<?php else: ?>
<p class="alert alert-error"><?php echo $this->__('Oops. You have no vouchers available. If you have placed a recent order using Credit Card or PayPal, please check back within 5 minutes.'); ?> <br> <?php echo $this->__('If you have placed an order using Cash on Delivery (COD), you will recieve your voucher within 2 working days.'); ?></p>
<?php endif ?>
