<div class="subscribe-email">
    <form action="<?php echo $this->getFormActionUrl() ?>" class="subscribe-form" method="post" id="newsletter-validate-detail">
        <div class="input-prepend inline">
            <span class="add-on"><i class="icon-envelope"></i></span><input type="text" size="16" id="prependedInput"  name="email" class="span2 input-text required-entry validate-email">
        </div>
        <button  type="submit" class="btn">Subscribe</button>

    </form>
</div>
<script type="text/javascript">
    //<![CDATA[
    var newsletterSubscriberFormDetail = new VarienForm('newsletter-validate-detail');
    //]]>
</script>